// 승률·레이팅 어긋남 문구 — quip-facts.ts 의 divergence 가 여는 셋째 갈래.
//
// 사건(한 번 참)도 특성(늘 참)도 아닌 **상태**다: 최근 25판 동안 지속되다 사라진다.
// 파일을 나눈 이유는 fact-jokes.ts 와 같다 — 여는 조건이 다른 축을 한 파일에 섞으면
// 발화 조건을 통제할 수 없다. 분량도 다르다: 이 축은 조건당 50줄 × 3언어라
// fact-jokes.ts 에 넣으면 그 파일이 두 배가 된다.
//
// ── 세 조건 (quip-facts.ts 의 breakevenWinRate 가 구간별 손익분기를 정한다) ──
//  winNoGain   그 레이팅 구간 손익분기보다 뚜렷이(±2판) 높게 이겼는데 순변화 ≤ 0
//              → 이길 때 조금 얻고 질 때 왕창 잃는 구간에 있다.
//  loseButGain 손익분기보다 뚜렷이 낮게 이겼는데 순변화 ≥ +15
//              → 위만 잡고 아래에 진 것. 승률로는 절대 안 보이는 흑자다.
//  flatEven    손익분기보다 뚜렷이 낮게 이겼는데 순변화 |±15| 미만
//              → 지는 날 싸게 지고 이기는 날 비싸게 이겨 정확히 본전.
//
// 손익분기가 왜 구간마다 다른가: docs/rating-threshold-research.md 2026-08-07 실측
// (750~999 ~17.5%, 1000~1999 ~49%, 2000~2249 ~56.5%, 2250~2499 ~64%, 2500~2749
// ~75%, 2750~2999 는 관측 범위(승률 90~99%) 안에서도 못 미침). 예전엔 60%/48%
// 고정값을 전 구간에 썼는데, 그 옆 주석 자체가 "구간마다 다르다"고 말하고
// 있었다(docs/rank-point-attempt.md 의 형제 조사, 미문서화) — 이제 실측 표로
// 코드와 주석이 일치한다.
//
// ── 톤 — app/jokes.ts 머리말 규칙 그대로. 이 파일에서 특히: ─────────
//  · **'강등'이라는 단어를 쓰지 않는다.** 강등은 단(myRank)이 실제로 떨어졌을 때만
//    fact-jokes.ts 의 rankChange 가 말한다. 여기는 레이팅 얘기다 — 레이팅 하락을
//    강등이라 부르면 거짓말이 된다.
//  · 숫자는 실측값(w·l·net)만 인용한다. "이기면 +8" 같은 대역 평균은 개별 사용자에게
//    부정확할 수 있어 문장에 박지 않는다 — "조금 얻고 왕창 잃는"으로 말한다.
//  · winNoGain 은 최상위가 아니어도 발생한다(아래쪽만 잡아도 net≤0 이 된다).
//    "당신은 정상이다"라고 단정하는 문장은 피하고, 구조("위쪽 손님이 없다")를 말한다.
//  · en/ja 는 번역이 아니라 같은 성격의 다른 문장이다. 맞추는 건 개수와 톤이다.

import type { Lang } from './i18n';
import type { QuipFacts } from '@/lib/tekken/quip-facts';

type Pool = Record<Lang, string[]>;

/** 순변화 표기: 양수에만 + 를 붙인다. */
const sign = (n: number) => (n > 0 ? `+${n}` : String(n));

function winNoGain(w: number, l: number, net: number): Pool {
  const n = sign(net);
  return {
    ko: [
      `${w}승 ${l}패에 레이팅 ${n}. 물건은 납품됐는데 대금이 안 들어옵니다.`,
      `이길 때는 동전으로 받고 질 때는 지폐로 냅니다. 약관에 작게 적혀 있었습니다.`,
      `승률은 흑자, 레이팅은 동결. 회계 담당은 시스템입니다.`,
      `여기서부터는 이겨도 잘 안 오릅니다. 정상 부근은 원래 공기가 희박합니다.`,
      `이길 사람을 거의 다 이겨두셔서, 시스템이 지갑을 닫았습니다.`,
      `이겨서 최저임금, 져서 도심 주차위반. 이 동네 물가입니다.`,
      `성과는 냈고 평가는 보류됐습니다. 인사팀 이름이 glicko 입니다.`,
      `유리천장은 회사에만 있는 게 아니었습니다.`,
      `시시포스도 승률만 보면 꽤 높았을 겁니다. 바위가 문제였지.`,
      `제로 금리 시대입니다. 원금을 지킨 것만으로도 선방입니다.`,
      `${w}승이 ${n}으로 정산됐습니다. 중개 수수료가 호쾌합니다.`,
      `위층 엘리베이터 버튼이 안 눌립니다. 만원이랍니다.`,
      `정상 부근에서는 한 발 미끄러지면 사흘 치 등반입니다. 산은 정직합니다.`,
      `이겨도 본전인 시장 — 경제학에서는 완전경쟁이라고 부릅니다.`,
      `지금 필요한 건 승리가 아니라 위층에서 내려올 손님입니다.`,
      `레이팅이 게으른 게 아니라 신중한 겁니다. 벌써 몇 주째 신중하지만요.`,
      `이기고도 못 받은 것을 어음이라고 합니다. 발행인은 시스템입니다.`,
      `승률 그래프는 우상향, 레이팅 그래프는 수평선. 둘 다 진짜라서 더 아픕니다.`,
      `정체 구간의 맨 앞차는 매칭 풀입니다. 경적은 효과가 없습니다.`,
      `이긴 상대들이 포인트를 안 들고 다닙니다. 소매치기도 빈 지갑 앞에선 웁니다.`,
      `레이팅 동결은 시스템식 존경입니다. 더 시험할 게 없다는 뜻이니까요.`,
      `프로 계약이었다면 "폼은 좋은데 순위가 안 움직인다"는 해설이 붙었을 장면입니다.`,
      `급여명세서는 없지만 일은 하셨습니다. 인턴십이라고 생각하십시오.`,
      `이 구간 손익분기는 6할이 넘습니다. 노동법 적용 제외 지역입니다.`,
      `이겨서 얻는 게 없으면, 이기는 이유는 철학과 소관이 됩니다.`,
      `지금 발목을 잡는 건 상대가 아니라 환율입니다.`,
      `많이 걷는데 제자리 — 러닝머신의 원리가 랭크에 이식됐습니다.`,
      `축의금은 냈는데 식사가 안 나오는 잔치입니다.`,
      `고도가 높아지면 산소도 포인트도 옅어집니다. 등산가들은 알고도 올라갑니다.`,
      `레이팅이 안 움직이는 게 아니라, 움직일 이유를 당신이 다 없앴습니다.`,
      `경비는 본인 부담, 성과는 회사 소유. 어디서 많이 본 계약서입니다.`,
      `이 스코어보드에 필요한 건 심판이 아니라 감사원입니다.`,
      `포인트가 아래로만 흐르는 구조입니다. 위로는 안 떨어집니다.`,
      `이만큼 이겼는데 레이팅이 조용하면, 침묵이 답입니다 — "이미 여기 주민이시잖아요."`,
      `깃발 꽂을 땅이 안 남았습니다. 정복 파트는 끝났습니다.`,
      `장부는 흑자, 현금은 그대로. 흑자도산 진행 중입니다.`,
      `승리가 유지보수 업무가 됐습니다. 유지보수팀엔 팁이 안 나옵니다.`,
      `남은 승진 자리는 위쪽 누군가의 은퇴 대기입니다.`,
      `이 고도에서 승리는 냉동으로 오고 패배는 생물로 옵니다.`,
      `자판기에 승리를 넣어도 아무것도 안 나옵니다. 고장이 아니라 설정입니다.`,
      `아래층 전원의 사다리 값을 당신이 대납하고 있습니다. 통이 크십니다.`,
      `이 높이에서 스코어보드가 재는 건 실력이 아니라 인내심입니다.`,
      `승수 재고는 쌓이는데 레이팅 창고가 입고를 거부합니다.`,
      `한 판 패배의 벌금이 세 판 치 승리입니다. 고급 주택가 주차요금이죠.`,
      `적금은 만기까지 부었습니다. 이자가 이겁니다.`,
      `완승 행진의 보상은 텅 빈 대진표입니다.`,
      `사다리 윗칸은 별매랍니다.`,
      `레이팅에 정년 보장이 나왔습니다. 이제 일을 안 해도 된답니다.`,
      `이길수록 본전이 안 되는 구조를, 위쪽 동네에서는 텃세라고 부릅니다.`,
      `"본전"이라는 단어가 이렇게 자주 나올 승률이 아닌데 말입니다.`,
    ],
    en: [
      `${w} wins, ${l} losses, rating ${n}. The goods were delivered and the invoice bounced.`,
      `Wins pay in coins here. Losses collect in bills.`,
      `Your win rate runs a surplus and your rating runs a freeze. The accountant is the system.`,
      `Nothing rises near the summit. The air is thin and so are the payouts.`,
      `You beat almost everyone worth points, so the system closed its wallet.`,
      `A win here is minimum wage. A loss is a downtown parking fine.`,
      `Performance: excellent. Compensation: under review. HR is called glicko.`,
      `The glass ceiling ships with ranked mode as well.`,
      `Sisyphus had a decent win rate too. The boulder was the problem.`,
      `Zero-interest era. Protecting the principal already counts as a result.`,
      `${w} wins settled for ${n}. The brokerage fee is remarkable.`,
      `The elevator button for the next floor will not light up. Full, apparently.`,
      `One slip near the peak costs three days of climbing. Mountains are honest.`,
      `A market where winning breaks even — economists call it perfect competition.`,
      `What you need is not another win. It is a visitor from upstairs.`,
      `The rating is not lazy. It is cautious. It has been cautious for weeks.`,
      `Winning without payment is called an IOU. The system signed it.`,
      `Win rate points up, rating points sideways. Both are true, which is the painful part.`,
      `Traffic jam near the top, and the car in front is the matchmaking pool.`,
      `The people you beat carry no points. Even pickpockets weep at empty wallets.`,
      `A frozen rating is the system paying respect: nothing left to test.`,
      `If this were a pro contract, the caption would read: great form, static ranking.`,
      `No pay slip, but the work got done. Consider it an internship.`,
      `Break-even here sits above sixty percent. Labor law does not reach this altitude.`,
      `When winning earns nothing, the reason to win becomes a philosophy question.`,
      `Your opponent is not stopping you. The exchange rate is.`,
      `Walking a lot and staying in place — the treadmill principle, ported to ranked.`,
      `You paid the gift money and the buffet never opened.`,
      `Oxygen and points thin out at the same altitude. Climbers go anyway.`,
      `The rating is not stuck. You removed every reason for it to move.`,
      `Expenses yours, profits theirs. A familiar contract.`,
      `This scoreboard does not need a referee. It needs an auditor.`,
      `Points only trickle downward here. Nothing drips up.`,
      `You won this much and the rating said nothing. The silence means: you already live here.`,
      `No land left for the flag. The conquest chapter is closed.`,
      `Profitable on paper, frozen in cash. A textbook paper bankruptcy.`,
      `Winning has become maintenance work, and nobody tips the maintenance crew.`,
      `The only promotion left is waiting for someone upstairs to retire.`,
      `At this height victories arrive frozen and losses arrive fresh.`,
      `The vending machine accepts wins and dispenses nothing. Not broken. Configured.`,
      `You are subsidizing the ladder for every floor below. Very generous of you.`,
      `Up here the scoreboard measures patience, not skill.`,
      `The win inventory grows and the rating warehouse refuses delivery.`,
      `One loss fines you three wins. Parking rates of a wealthy district.`,
      `You paid the installments to maturity. This is the interest.`,
      `The reward for clearing the field is an empty field.`,
      `The upper rungs of the ladder are sold separately.`,
      `Your rating received tenure. It no longer has to do anything.`,
      `Winning into a break-even is what the upper floors call a housewarming ritual.`,
      `The word "break-even" was never meant for a record like this. And yet.`,
    ],
    ja: [
      `${w}勝${l}敗でレートは${n}。納品は済んだのに入金がありません。`,
      `勝ちは小銭で支払われ、負けは札で回収されます。約款に小さく書いてあります。`,
      `勝率は黒字、レートは凍結。経理担当はシステムです。`,
      `頂上付近では何も増えません。空気も、ポイントも。`,
      `勝てる相手をほぼ勝ち尽くしたので、システムが財布を閉じました。`,
      `勝って最低賃金、負けて都心の駐車違反。この街の物価です。`,
      `成果は出た、査定は保留。人事部の名前は glicko です。`,
      `ガラスの天井はランクマッチにも標準装備でした。`,
      `シーシュポスも勝率だけなら悪くなかったはずです。岩が問題で。`,
      `金利ゼロ時代、元本を守れただけ上出来です。`,
      `${w}勝が${n}で精算されました。手数料が豪快です。`,
      `上の階のエレベーターボタンが点きません。満員だそうです。`,
      `頂上付近は一歩滑ると三日分の登り直し。山は正直です。`,
      `勝っても損益ゼロの市場。経済学では完全競争と呼びます。`,
      `今必要なのは勝利ではなく、上の階からの来客です。`,
      `レートは怠けているのではなく慎重なのです。もう何週間も。`,
      `勝ったのに支払われないものを手形と呼びます。振出人はシステム。`,
      `勝率は右肩上がり、レートは水平線。両方とも本当なのが一番つらい。`,
      `渋滞の先頭はマッチングプールです。クラクションは効きません。`,
      `倒した相手がポイントを持っていません。スリも空の財布には泣きます。`,
      `レート凍結はシステム流の敬意です。もう試すことがない、という意味なので。`,
      `プロ契約だったら「調子は良いのに順位が動かない」と実況される場面です。`,
      `給与明細はありませんが、仕事はしました。インターンだと思いましょう。`,
      `この帯の損益分岐は6割超え。労働基準法の圏外です。`,
      `勝っても増えないなら、勝つ理由は哲学の管轄になります。`,
      `足止めしているのは相手ではなく為替レートです。`,
      `たくさん歩いて同じ場所。ランニングマシンの原理がランクに移植されています。`,
      `ご祝儀は払ったのに料理が出てこない披露宴です。`,
      `高度が上がると酸素もポイントも薄くなります。登山家は知っていて登ります。`,
      `レートが動かないのではなく、動く理由をあなたが全部片付けたのです。`,
      `経費は自腹、成果は会社のもの。見覚えのある契約書です。`,
      `このスコアボードに必要なのは審判ではなく会計監査です。`,
      `ポイントは下にしか流れない構造です。上には滴りません。`,
      `これだけ勝って無言のレートなら、沈黙が答えです。「もう住民でしょう」と。`,
      `旗を立てる土地が残っていません。征服の章は終わりました。`,
      `帳簿は黒字、現金は据え置き。黒字倒産が進行中です。`,
      `勝利がメンテナンス業務になりました。メンテにチップは出ません。`,
      `残った昇進枠は、上の誰かの引退待ちです。`,
      `この高度では勝利は冷凍で届き、敗北は生で届きます。`,
      `自販機に勝利を入れても何も出ません。故障ではなく仕様です。`,
      `下の階全員のはしご代をあなたが負担しています。太っ腹ですね。`,
      `この高さでスコアボードが測るのは実力ではなく忍耐です。`,
      `勝ち星の在庫は増えるのに、レートの倉庫が受け取りを拒否します。`,
      `一敗の罰金が三勝分。高級住宅街の駐車料金です。`,
      `積立は満期まで払いました。利息がこれです。`,
      `完全勝利の報酬は、誰もいない対戦表です。`,
      `はしごの上の段は別売りだそうです。`,
      `レートに終身在職権が付きました。もう働かなくていいそうです。`,
      `勝つほど元が取れない仕組みを、上の街では「ようこそ」と呼ぶらしいです。`,
      `「損益分岐」という単語がこんなに似合う勝率ではないはずなのですが。`,
    ],
  };
}

function loseButGain(w: number, l: number, net: number): Pool {
  const n = sign(net);
  return {
    ko: [
      `${w}승 ${l}패에 레이팅 ${n}. 지는 법을 아는 분입니다.`,
      `지고도 벌었습니다. 요즘 이런 장사가 없습니다.`,
      `전적은 적자, 레이팅은 흑자. 감사가 나와도 답은 있습니다 — 위쪽하고만 붙었다고.`,
      `강한 상대에게 낸 수업료가 배당으로 돌아오는 중입니다.`,
      `패배 보험을 만기 환급형으로 들어두셨군요.`,
      `승률이 등을 돌린 사이에 시스템이 당신 편을 들었습니다.`,
      `지면서 오르는 건 위쪽하고만 싸운 사람의 특권입니다.`,
      `이건 연패가 아니라 원정 경기입니다. 원정은 져도 수당이 나옵니다.`,
      `승률에게 혼나고 레이팅에게 칭찬받는 중입니다. 부모가 둘이면 이렇게 됩니다.`,
      `남들은 이겨서 올라가는데, 당신은 협상으로 올라가고 있습니다.`,
      `싸게 지고 비싸게 이기는 포트폴리오. 헤지가 완벽합니다.`,
      `지는 상대를 잘 고르셨습니다. 그것도 엄연히 기술입니다.`,
      `은메달만 모았는데 종합 순위가 올랐습니다. 종목 선택의 승리입니다.`,
      `레이팅은 승패가 아니라 명단을 봅니다. 당신 명단이 화려했을 뿐입니다.`,
      `체급 위로만 도전한 수당이 입금됐습니다. 멍은 들었지만요.`,
      `5할 밑에서 플러스면, 진 판들이 전부 상소문이었다는 뜻입니다. 전부 인용됐고요.`,
      `이길 때 크게, 질 때 싸게. 장사의 기본을 랭크에서 하고 계십니다.`,
      `전적표는 후퇴, 통장은 전진. 통장을 믿으십시오.`,
      `레이팅에 위층 지문이 묻어 있습니다. 훈장 비슷한 겁니다.`,
      `진 상대들이 전부 당신보다 부자였습니다. 상속이 포인트로 들어오는 중입니다.`,
      `싸움에서는 지고 재판에서 이겼습니다.`,
      `이 전적에 플러스라면 매칭이 당신을 존중한다는 뜻입니다. 위로만 붙여주는 존중.`,
      `남의 잔치에 가서 얻어맞고 답례품만 챙겨 왔습니다.`,
      `경험치는 원래 진 쪽이 더 받습니다. 여기는 포인트도 그렇게 주네요.`,
      `위와 싸워서 진 것은 감가상각이 거의 없습니다. 지금 그 회계를 쓰고 계십니다.`,
      `패전 처리 투수가 평균자책점 1위인 상황입니다. 기록원이 곤란해합니다.`,
      `프로였다면 "성적은 아쉽지만 일정을 보면 남는 장사"라는 분석 기사가 났을 겁니다.`,
      `지갑을 잃어버렸는데 신용등급이 올랐습니다.`,
      `진 판의 절반이 도전이었고, 시스템은 도전에 이자를 쳐줍니다.`,
      `이달의 사원은 못 됐지만 스톡옵션은 들어왔습니다.`,
      `승률은 체면이고 레이팅은 실속입니다. 남는 건 실속 쪽입니다.`,
      `아래에는 안 진 성적표입니다. 낙제점이 없으니 진급은 됩니다.`,
      `멍 하나당 수당이 붙는 스파링 파트너 급여 체계입니다. 합법입니다.`,
      `패배를 조공이라 부르면 굴욕이고, 투자라 부르면 절세입니다.`,
      `눈물 반, 포인트 반으로 상승 중입니다.`,
      `지고도 위에 있다면 계단이 아니라 에스컬레이터를 타신 겁니다.`,
      `전장에서 지고 외교에서 이기는 수. 역사책 단골입니다.`,
      `이 승률로 오르는 중이면 시스템이 당신 미래에 선불을 넣은 겁니다.`,
      `위층과의 접전은 져도 요금이 안 나옵니다. 지금 합법적 무임승차 중입니다.`,
      `패배들이 노조를 결성하기 전에 지금 구조를 즐기십시오.`,
      `스코어보드는 못 알아봤지만 정산 시스템은 알아봤습니다.`,
      `많이 진 날에도 곳간이 차는 건 지주의 삶입니다.`,
      `점수 안 나가는 패배만 골라 하셨습니다. 큐레이션 감각이 있습니다.`,
      `이 속도면 승률 4할대로 정상에 서는 최초 사례가 됩니다. 논문감입니다.`,
      `적게 이기고 크게 받는 구조. 보험사가 연구해야 할 인재입니다.`,
      `진 판들이 이력서가 되고 있습니다 — "상위권과 교전 다수" 한 줄.`,
      `체면은 전사했지만 포인트는 생환했습니다.`,
      `오르는 이유를 승률에서 찾지 마십시오. 대진 명단에서 찾으십시오.`,
      `지는 날에도 남는 게 있는 건 구조를 잘 짠 사람뿐입니다. 우연이어도 축하드립니다.`,
      `승수는 모자란데 잔고는 늘었습니다. 랭크가 은행이었으면 조사 나왔습니다.`,
    ],
    en: [
      `${w} wins, ${l} losses, rating ${n}. You have mastered losing correctly.`,
      `Losing on paper, earning in points. The audit will find nothing.`,
      `You lost the fights and won the settlement.`,
      `Tuition paid to stronger players has started paying dividends.`,
      `Your loss insurance turned out to have a refund clause. Well chosen.`,
      `The win rate turned its back and the system took your side.`,
      `Rising while losing is reserved for people who only pick fights upstairs.`,
      `These are not defeats. They are away games, and away games pay allowances.`,
      `Scolded by the win rate, praised by the rating. Two parents, one household.`,
      `Everyone else climbs by winning. You are climbing by negotiation.`,
      `Cheap losses, expensive wins — a perfectly hedged portfolio.`,
      `You chose whom to lose to. Technically, that is also a skill.`,
      `A shelf of silver medals, and the overall ranking rose anyway.`,
      `The rating does not count wins. It reads the guest list. Yours is impressive.`,
      `Punching up comes with a salary, apparently. It just cleared.`,
      `Below fifty percent and still positive — every loss was an appeal, and all were granted.`,
      `Win big, lose cheap. You are running a business, not a record.`,
      `The scoreboard says retreat. The bank statement says advance. Trust the bank.`,
      `There are fingerprints from the upper floors on your rating. That is a commendation.`,
      `You keep losing to people richer than you. The points are the inheritance.`,
      `Lost the fight, won the lawsuit.`,
      `A plus sign on this record means matchmaking respects you: upward bookings only.`,
      `You attended the wrong party, took the beating, and left with the gift bag.`,
      `The losing side earns the experience. Here they hand out rating with it.`,
      `Losses against the top barely depreciate. You are using that accounting.`,
      `The relief pitcher with the best ERA in the league. The scorekeeper is confused.`,
      `If this were a pro career, the column would read: poor record, excellent schedule.`,
      `You lost your wallet and your credit score went up.`,
      `Half the losses were challenges, and the system pays interest on challenges.`,
      `Not employee of the month, but the stock options vested.`,
      `Win rate is face. Rating is substance. Substance is what compounds.`,
      `No failing grades against the floors below — the report card promotes you anyway.`,
      `Paid by the bruise: the sparring partner contract, fully legal.`,
      `Call the losses tribute and it is humiliation. Call them investment and it is tax planning.`,
      `Half tears, half points. It still counts as climbing.`,
      `Losing and rising means you found the escalator while others fought the stairs.`,
      `Lose the battle, win the diplomacy. The history books approve.`,
      `Climbing at this win rate means the system prepaid for your future.`,
      `Close losses upstairs ride free. You are fare-dodging, legally.`,
      `Enjoy the arrangement before the losses unionize.`,
      `The scoreboard did not recognize you. The settlement system did.`,
      `The barn fills even on losing days. That is landlord life.`,
      `You curated losses that cost nothing. Impeccable taste.`,
      `At this pace you will summit at a forty percent win rate. Someone should write the paper.`,
      `Win rarely, collect largely. Insurance companies study people like you.`,
      `The losses are becoming a résumé: extensive combat experience with the top brackets.`,
      `Dignity fell in action. The points came home.`,
      `Do not look for the reason in the win rate. Look at the guest list.`,
      `Coming out ahead on losing days is design, not luck. Congratulations either way.`,
      `Short on wins, up on balance. If ranked were a bank, there would be an inquiry.`,
    ],
    ja: [
      `${w}勝${l}敗でレート${n}。正しい負け方をご存じの方です。`,
      `負けて稼ぐ。今どき珍しい商売です。`,
      `戦績は赤字、レートは黒字。監査が来ても答えられます — 上としか戦っていない、と。`,
      `強い相手に払った授業料が、配当になって戻ってきています。`,
      `敗北保険が満期返戻型でした。良い契約です。`,
      `勝率に見放された間に、システムが味方につきました。`,
      `負けながら上がるのは、上としか戦わない人の特権です。`,
      `連敗ではなくアウェー戦です。アウェーは負けても手当が出ます。`,
      `勝率に叱られ、レートに褒められる。親が二人いるとこうなります。`,
      `他人は勝って登る。あなたは交渉で登っている。`,
      `安い敗北と高い勝利。ヘッジが完璧なポートフォリオです。`,
      `負ける相手の選び方が上手い。それも立派な技術です。`,
      `銀メダルばかり集めたのに総合順位が上がりました。種目選びの勝利です。`,
      `レートは勝敗ではなく名簿を見ます。あなたの名簿が豪華だっただけです。`,
      `格上に挑んだ分の手当が振り込まれました。あざは残りましたが。`,
      `5割以下でプラスなら、負けは全部上訴だったということです。全部通りました。`,
      `勝つ時は大きく、負ける時は安く。商売の基本をランクでやっています。`,
      `戦績表は後退、通帳は前進。通帳を信じましょう。`,
      `レートに上の階の指紋が付いています。勲章のようなものです。`,
      `負けた相手が全員あなたより金持ちでした。相続がポイントで届いています。`,
      `喧嘩には負けて、裁判には勝ちました。`,
      `この戦績でプラスは、マッチングがあなたを尊重している証拠です。上としか組ませない尊重。`,
      `よその宴会で殴られて、引き出物だけ持って帰ってきました。`,
      `経験値は負けた側が多くもらうもの。ここではポイントもそう配られました。`,
      `格上への敗北は減価償却がほぼゼロ。その会計をお使いです。`,
      `敗戦処理投手が防御率1位。記録員が困っています。`,
      `プロだったら「成績は悪いが日程は最高」という分析記事が出る場面です。`,
      `財布を落としたのに信用スコアが上がりました。`,
      `敗北の半分は挑戦で、システムは挑戦に利息を付けます。`,
      `今月の社員にはなれませんでしたが、ストックオプションは付与されました。`,
      `勝率は体面、レートは実利。残るのは実利です。`,
      `下には負けていない成績表。赤点がないので進級はできます。`,
      `あざの数だけ支払われる、スパーリングパートナーの給与体系。合法です。`,
      `敗北を貢ぎ物と呼べば屈辱、投資と呼べば節税です。`,
      `涙半分、ポイント半分で上昇中です。`,
      `負けたのに上にいるなら、階段ではなくエスカレーターでした。`,
      `戦場で負けて外交で勝つ。歴史書の定番です。`,
      `この勝率で上昇中なら、システムがあなたの将来に前払いしています。`,
      `上の階との接戦は負けても運賃がかかりません。合法的なただ乗り中です。`,
      `敗北たちが労働組合を作る前に、今の構造を楽しんでください。`,
      `スコアボードは気づきませんでしたが、精算システムは気づきました。`,
      `負けた日にも蔵が埋まるのは、地主の暮らしです。`,
      `ポイントの出ない敗北だけを選んで打ちました。目利きです。`,
      `このままなら勝率4割台で頂上に立つ初の事例です。論文になります。`,
      `少なく勝って大きく受け取る。保険会社が研究すべき人材です。`,
      `敗北が履歴書になりつつあります。「上位帯と交戦多数」の一行。`,
      `体面は戦死しましたが、ポイントは生還しました。`,
      `上がる理由を勝率に探さないでください。対戦名簿に探してください。`,
      `負けた日にも残る物があるのは、構造を組んだ人だけです。偶然でも、おめでとうございます。`,
      `勝ち星は足りないのに残高は増えました。ランクが銀行なら調査が入っています。`,
    ],
  };
}

function flatEven(w: number, l: number, net: number): Pool {
  const n = sign(net);
  return {
    ko: [
      `${w}승 ${l}패, 레이팅 변화 ${n}. 시스템도 판단을 보류했습니다.`,
      `5할 아래인데 제자리라면, 싸게 지고 비싸게 이겼다는 뜻입니다. 신기하게 본전.`,
      `보합세입니다. 주식이었으면 거래량 부족으로 기사도 안 났습니다.`,
      `이번 25판은 무승부입니다. 철권에 없는 결과를 발명하셨습니다.`,
      `레이팅이 당신을 무시하는 게 아니라, 아직 결론이 없는 겁니다.`,
      `순환선에 타셨습니다. 풍경은 바뀌는데 역은 그대로입니다.`,
      `이 구간의 항해 일지: 바람 없음, 파도 없음, 진전 없음.`,
      `많이 걸었고 위치는 같습니다. 러닝머신은 원래 그 용도입니다.`,
      `당신 배치를 정하는 회의가 몇 주째입니다. 잠정 결론은 "일단 거기".`,
      `싸게 지고 싸게 이기는, 본전의 장인이 되셨습니다.`,
      `전진도 후퇴도 아닌 상태를 군대에서는 대치라고 부릅니다.`,
      `레이팅 그래프에 자를 대고 그을 수 있는 흔치 않은 시기입니다.`,
      `물에 뜨는 법은 완벽히 익히셨습니다. 남은 항목은 헤엄입니다.`,
      `어제의 당신과 오늘의 당신이 호각입니다. 문제는 둘 다 5할 밑이라는 것.`,
      `평형 상태 — 화학에서는 안정, 랭크에서는 정체라고 부릅니다.`,
      `회전문 안입니다. 움직임은 있는데 입장도 퇴장도 아닙니다.`,
      `점수를 잃지 않는 재주와 얻지 않는 재주를 동시에 갖추셨습니다.`,
      `무풍지대입니다. 돛 문제인지 바람 문제인지는 다음 25판이 증언합니다.`,
      `시스템의 침묵은 무죄도 유죄도 아닌 "경과 관찰"입니다.`,
      `현상 유지에도 유지비가 듭니다. 청구서는 승률 앞으로 갑니다.`,
      `왕복 티켓으로 통근 중이십니다. 마일리지는 안 쌓입니다.`,
      `오르지도 내리지도 않는 엘리베이터. 버튼은 눌려 있습니다. 아마도.`,
      `진폭은 있는데 변위가 없습니다. 물리학은 이걸 진동이라 부릅니다.`,
      `이대로면 다음 달에도 같은 자리에서 같은 농담을 듣게 됩니다.`,
      `레이팅이 외우기 좋은 숫자에 당신을 주차해뒀습니다. 배려일 수 있습니다.`,
      `스크린세이버 상태입니다. 꺼진 건 아닌데 뭘 하는 것도 아닌.`,
      `광합성 중이십니다. 자라지도 시들지도 않는.`,
      `제자리걸음도 걸음이라, 피로만은 정직하게 쌓입니다.`,
      `이긴 날 수입과 진 날 지출이 끝전까지 맞습니다. 가계부의 모범, 랭크의 정체.`,
      `필요한 건 연승도 연패도 아니고, 어느 쪽으로든 기우는 것입니다.`,
      `이 승률에 제자리면 진 건 위쪽, 이긴 건 아래쪽이었다는 겁니다. 교통정리는 완벽했습니다.`,
      `어항 안에서는 아무리 헤엄쳐도 어항 크기만큼입니다.`,
      `박스권 매매 중입니다. 저점 매수가 아니라 그냥 박스에 사는 중.`,
      `변화 없음도 데이터입니다 — "여기가 당신 주소"라는 데이터.`,
      `시소의 정중앙에 앉으셨습니다. 재미는 양쪽 끝에 있는데요.`,
      `오늘도 잃은 것 없이 무사히. 그게 목표였다면 달성입니다.`,
      `이 그래프에서 변화 찾기는 숨은그림찾기 난이도입니다.`,
      `한 달 뒤 이 구간은 스크롤이 빨라질 겁니다. 아무 일도 없었으니까.`,
      `레이팅이 닻을 내렸습니다. 출항 신호는 당신 손에 있습니다.`,
      `패배가 싸게 먹히는 건 다행인데, 승리도 헐값에 팔리는 중입니다.`,
      `정체는 후퇴가 아닙니다. 다만 통행료는 계속 나갑니다 — 시간이라는 통행료가.`,
      `평지에서 페달을 밟는 중입니다. 순위는 언덕이 나와야 갈립니다.`,
      `스코어보드가 가부동수입니다. 캐스팅보트는 다음 25판에 있습니다.`,
      `움직이지 않는 레이팅 감상법: 액자라고 생각하면 편해집니다.`,
      `무승부 전문가라는 직업이 있었으면 스카우트가 왔을 겁니다.`,
      `제로섬 게임에서 정확히 0을 들고 나오는 것도 일종의 기록입니다.`,
      `층과 층 사이에 계십니다. 천장도 바닥도 안 보이지만 계단은 양쪽으로 열려 있습니다.`,
      `이 구간 요약: 특이사항 없음. 쓸 게 없다는 게 특이사항입니다.`,
      `시스템이 당신 서류를 "보류함"에 넣었습니다. 도장은 당신이 찍는 겁니다.`,
      `수평선은 바라보는 곳이지 주소지가 아닙니다.`,
    ],
    en: [
      `${w} wins, ${l} losses, net ${n}. Even the system reserved judgment.`,
      `Below fifty percent and perfectly flat: you lose cheap and win expensive. Somehow it cancels.`,
      `A sideways market. If this were a stock, the volume would be too low for the news.`,
      `This window ends in a draw. Tekken does not have draws. You invented one.`,
      `The rating is not ignoring you. It simply has no verdict yet.`,
      `You boarded the loop line. The scenery changes, the station does not.`,
      `Ship log for this stretch: no wind, no waves, no progress.`,
      `You walked a great deal and remain in place. That is what treadmills are for.`,
      `The committee on your placement has met for weeks. Interim ruling: right there.`,
      `Losing cheap, winning cheap — an artisan of the break-even.`,
      `Neither advance nor retreat. The military word is standoff.`,
      `One of the rare eras where a ruler fits your rating graph.`,
      `Floating: mastered. Swimming: the remaining item.`,
      `Yesterday-you and today-you are evenly matched. Unfortunately both sit below fifty.`,
      `Equilibrium — chemistry calls it stability, ranked calls it stagnation.`,
      `Inside the revolving door: motion, but neither entrance nor exit.`,
      `The talent of losing no points and the talent of gaining none, acquired together.`,
      `Dead calm. Sail or wind, the next window will testify.`,
      `The silence of the system is neither acquittal nor conviction. It is observation.`,
      `The status quo has running costs. Yours are billed to the win rate.`,
      `Commuting on a round-trip ticket. No miles accrue.`,
      `An elevator that neither rises nor falls. The button is pressed. Probably.`,
      `Amplitude without displacement. Physics calls this oscillation.`,
      `Stay the course and next month features this exact joke again.`,
      `The rating parked you at a memorable number. Possibly out of kindness.`,
      `Screensaver mode: not off, not exactly doing anything.`,
      `Photosynthesis: neither growing nor wilting.`,
      `Marching in place is still marching. The fatigue is real. The distance is not.`,
      `Winning-day income matches losing-day expenses to the cent. Model bookkeeping, stationary ranking.`,
      `What you need is neither a streak nor a slump. Any tilt would do.`,
      `Flat at this rate means the losses were upstairs and the wins downstairs. Flawless traffic control.`,
      `However hard you swim, an aquarium is aquarium-sized.`,
      `Range-bound trading — except you are not buying the dip, you are living in it.`,
      `No change is also data. It reads: this is your address.`,
      `You sat at the exact center of the seesaw. The fun is at the ends.`,
      `Another day, nothing lost. If that was the goal, achieved.`,
      `Finding movement in this graph is a hidden-object puzzle.`,
      `A month from now you will scroll past this stretch quickly. Nothing happened in it.`,
      `The rating dropped anchor. The departure signal is in your hand.`,
      `Losses coming cheap is good news. Wins selling cheap is the same news.`,
      `Stagnation is not retreat. The toll still runs — the toll being time.`,
      `Pedaling on flat ground. The standings change when a hill shows up.`,
      `The scoreboard is a tied vote. The casting ballot belongs to the next window.`,
      `How to enjoy an unmoving rating: think of it as a framed picture.`,
      `If draw-specialist were a profession, the scouts would have called.`,
      `Extracting exactly zero from a zero-sum game is a record of its own kind.`,
      `A floor between floors — no ceiling in sight, no bottom either, stairs open both ways.`,
      `Summary of the period: nothing to report. That is the report.`,
      `The system filed you under pending. The stamp is yours to apply.`,
      `The horizon is something to look at, not a mailing address.`,
    ],
    ja: [
      `${w}勝${l}敗、レート変動${n}。システムも判断を保留しました。`,
      `5割以下で横ばいなら、安く負けて高く勝った計算です。不思議と元通り。`,
      `保ち合い相場です。株なら出来高不足で記事にもなりません。`,
      `この25戦は引き分けです。鉄拳にない結果を発明しました。`,
      `レートは無視しているのではなく、結論が出ていないだけです。`,
      `環状線に乗りました。景色は変わるのに駅は同じです。`,
      `この区間の航海日誌:風なし、波なし、進展なし。`,
      `よく歩いて、同じ場所です。ランニングマシンは本来その用途です。`,
      `あなたの配属会議が数週間続いています。暫定結論は「一旦そこで」。`,
      `安く負けて安く勝つ、損益ゼロの職人になりました。`,
      `前進でも後退でもない状態を、軍隊では膠着と呼びます。`,
      `レートのグラフに定規が当てられる、めったにない時期です。`,
      `浮くことは完璧に覚えました。残る項目は泳ぎです。`,
      `昨日のあなたと今日のあなたが互角です。問題は両方5割以下なこと。`,
      `平衡状態 — 化学では安定、ランクでは停滞。`,
      `回転ドアの中です。動いてはいるが、入場でも退場でもない。`,
      `ポイントを失わない才能と、得ない才能を同時に習得しました。`,
      `凪です。帆か風か、次の25戦が証言します。`,
      `システムの沈黙は無罪でも有罪でもなく「経過観察」です。`,
      `現状維持にも維持費がかかります。請求書は勝率宛てです。`,
      `往復切符で通勤中です。マイルは貯まりません。`,
      `上がりも下がりもしないエレベーター。ボタンは押してあります。たぶん。`,
      `振幅はあるのに変位がない。物理学ではこれを振動と呼びます。`,
      `この調子なら来月も同じ場所で同じ冗談を聞くことになります。`,
      `レートが覚えやすい数字にあなたを駐車させました。親切かもしれません。`,
      `スクリーンセーバー状態です。消えてはいないが、何かしているわけでもない。`,
      `光合成中です。育ちも枯れもしない。`,
      `足踏みも歩みは歩み。疲労だけは正直に貯まります。`,
      `勝った日の収入と負けた日の支出がぴったり一致。家計簿の模範、ランクの停滞。`,
      `必要なのは連勝でも連敗でもなく、どちらかに傾くことです。`,
      `この勝率で横ばいなら、負けは上に、勝ちは下に。交通整理は完璧です。`,
      `水槽の中では、どれだけ泳いでも水槽のぶんだけです。`,
      `ボックス相場です。押し目買いではなく、箱に住んでいます。`,
      `変化なしもデータです。「ここがあなたの住所」というデータ。`,
      `シーソーのど真ん中に座りました。楽しいのは両端なのですが。`,
      `今日も失うものなくご無事で。それが目標なら達成です。`,
      `このグラフから変化を探すのは間違い探しの難易度です。`,
      `一ヶ月後、この区間はスクロールが速くなります。何も起きていないので。`,
      `レートが錨を下ろしました。出航の合図はあなたの手元にあります。`,
      `負けが安いのは朗報ですが、勝ちも安売り中です。`,
      `停滞は後退ではありません。ただし通行料は出続けます — 時間という通行料が。`,
      `平地でペダルを漕いでいます。順位が動くのは坂からです。`,
      `スコアボードは可否同数。キャスティングボートは次の25戦にあります。`,
      `動かないレートの鑑賞法:額縁だと思えば楽になります。`,
      `引き分け専門家という職業があれば、スカウトが来ていました。`,
      `ゼロサムゲームからきっかりゼロを持ち帰るのも、一種の記録です。`,
      `階と階の間にいます。天井も床も見えませんが、階段は両方向に開いています。`,
      `この区間の要約:特記事項なし。書くことがないのが特記事項です。`,
      `システムがあなたの書類を「保留」に入れました。判子を押すのはあなたです。`,
      `水平線は眺める場所であって、住所ではありません。`,
    ],
  };
}

/**
 * divergence 상태에 맞는 pool 을 돌려준다. 상태가 없으면 빈 배열 —
 * 그러면 pickJoke 의 사다리가 이 갈래를 그냥 지나간다.
 */
export function divergePool(f: QuipFacts | null, lang: Lang): string[] {
  const d = f?.divergence;
  if (!d) return [];
  const make =
    d.kind === 'winNoGain' ? winNoGain : d.kind === 'loseButGain' ? loseButGain : flatEven;
  return make(d.wins, d.losses, d.net)[lang];
}
